### ISSUE TITLE
Button: Control variant needs better focus (ring) indication

### ISSUE THREAD

**Issue by ItsJonQ** [ItsJonQ/g2#108]
<img width="152" alt="Screen Shot 2020-11-14 at 11 30 03 AM" src="https://user-images.githubusercontent.com/2322354/99151971-e548a980-266c-11eb-8c1f-74c67d789526.png">

It's currently near impossible to see if a `<Button isControl isSubtle />` is focused.
This is useful for when `<Button />` is rendered within a `<ButtonGroup />` - especially for <kbd>Tab</kbd> based interactions.

**Comment by ItsJonQ** [comment]
cc'ing @jasmussen 😊

**Comment by jasmussen** [comment]
Yep, that's a good one. For now I think we'll want to reimplement the focus style mostly as it exists already:

![focus](https://user-images.githubusercontent.com/1204802/99255288-00a1e900-2814-11eb-8c5f-5b8aeaea4c06.gif)

That is, 1.5px blue border, and when it's close to a toggled state or something that otherwise has insufficient contrast against the blue, add a 1px white border inside. I've done it in cases with a stacked box shadow.

**Comment by ItsJonQ** [comment]
> For now I think we'll want to reimplement the focus style mostly as it exists already

Can do 👍 !

**Comment by jasmussen** [comment]
Once systematized, we can explore how and whether you polish this up further 👌
